[2024-09-15 10:42:18,183] INFO _log() L97   127.0.0.1 - - [15/Sep/2024 10:42:18] "GET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1" 200 - - call_trace=C:\projetospos\MVP-Sprint3\MVP-Sprint2-Backend\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-09-15 10:42:18,184] INFO _log() L97   127.0.0.1 - - [15/Sep/2024 10:42:18] "GET /openapi/static/css/swagger-ui.css HTTP/1.1" 200 - - call_trace=C:\projetospos\MVP-Sprint3\MVP-Sprint2-Backend\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-09-15 10:42:18,362] INFO _log() L97   127.0.0.1 - - [15/Sep/2024 10:42:18] "GET /openapi/static/images/swagger.svg HTTP/1.1" 200 - - call_trace=C:\projetospos\MVP-Sprint3\MVP-Sprint2-Backend\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-09-15 10:42:18,593] INFO _log() L97   127.0.0.1 - - [15/Sep/2024 10:42:18] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\projetospos\MVP-Sprint3\MVP-Sprint2-Backend\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-09-15 10:42:24,388] ERROR log_exception() L838  Exception on /consulta_cep/{cep} [GET] - call_trace=C:\projetospos\MVP-Sprint3\MVP-Sprint2-Backend\env\Lib\site-packages\flask\app.py L838 
Traceback (most recent call last):
  File "C:\projetospos\MVP-Sprint3\MVP-Sprint2-Backend\env\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\projetospos\MVP-Sprint3\MVP-Sprint2-Backend\env\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\projetospos\MVP-Sprint3\MVP-Sprint2-Backend\env\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\projetospos\MVP-Sprint3\MVP-Sprint2-Backend\env\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\projetospos\MVP-Sprint3\MVP-Sprint2-Backend\env\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\projetospos\MVP-Sprint3\MVP-Sprint2-Backend\env\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
TypeError: consulta_cep() missing 1 required positional argument: 'cep'
[2024-09-15 10:42:24,397] INFO _log() L97   127.0.0.1 - - [15/Sep/2024 10:42:24] "[35m[1mGET /consulta_cep/{cep} HTTP/1.1[0m" 500 - - call_trace=C:\projetospos\MVP-Sprint3\MVP-Sprint2-Backend\env\Lib\site-packages\werkzeug\_internal.py L97  
